version: "3.3"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  tts_worker:
    build:
      context: ./tts
      dockerfile: DockerfileWorker
    depends_on:
      - rabbitmq

  stt:
    build:
      context: ./stt
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  cv:
    build:
      context: ./cv
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
