version: "3.3"

services:
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  tts_worker:
    build:
      context: ./tts
      dockerfile: DockerfileWorker
    depends_on:
      - rabbitmq
      
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
