version: "3.8"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tts
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
