version: "3.3"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  stt:
    build:
      context: ./stt
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
