version: "3.8"

services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tts

  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
